### ISSUE TITLE
over data quota

### ISSUE THREAD

**Issue by ckromero** [manthanraja/mastering-unity-shaders-and-effects#1]
Hi - looks like you're getting good traffic:
--> git lfs clone https://github.com/PacktPublishing/mastering-unity-shaders-and-effects.git
Cloning into 'mastering-unity-shaders-and-effects'...
remote: Counting objects: 18, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 18 (delta 7), reused 18 (delta 7), pack-reused 0
Unpacking objects: 100% (18/18), done.
Checking connectivity... done.
Git LFS: (0 of 1 files) 0 B / 276.70 MB  
batch response: http: This repository is over its data quota. Purchase more data packs to restore access.
Docs: https://help.github.com/articles/purchasing-additional-storage-and-bandwidth-for-an-organization/

**Comment by ckromero** [comment]
so just to be clear I can't download the examples in the book which would be really, really useful... can you talk to your publisher about adding some more data packs?
thanks

**Comment by ghost** [comment]
Hi @ckromero, Thank you for raising this issue. We have resolved the issue and you will be able to download the examples now. In case if you come across any other issue, please feel free to contact us by emailing us at [http://www.packtpub.com/submit-errata](http://www.packtpub.com/submit-errata).

**Comment by ckromero** [comment]
I have the files now, thank you!
