### ISSUE TITLE
package will not decompress

### ISSUE THREAD

**Issue by danamuise** [manthanraja/mastering-unity-shaders-and-effects#2]
Please check the downloadable zip file.

**Comment by ghost** [comment]
Hello @danamuise, we are sorry to hear that you have an issue with the package. Can you please elaborate what error are you getting when you try to decompress it? We will be able to resolve the issue only after we get more clarity on it.

**Comment by danamuise** [comment]
after downloading (and unzipping) I tried to import the Unity package. I received an error "could not decompress package". I re-dowloaded the file and tried again with same results. It may be my machine but I'm just saying you should test it out and make sure it works for the sake of your other customers.

**Comment by ghost** [comment]
@danamuise, did you download the package using **Git LFS**? Since the Unity package file was greater than 100 MB, we have uploaded it using **Git LFS**. To download the entire code bundle, you can use the command ```git lfs clone https://github.com/PacktPublishing/mastering-unity-shaders-and-effects.git``` from **Git Shell**. This instruction is also mentioned in **README.md** file.

**Comment by danamuise** [comment]
Yeah. Did you check it? Look, Im doing you a favor by reporting the issue.

**Comment by danamuise** [comment]
Yeah. Did you check it? Look, Im doing you a favor by reporting the issue.

**Comment by ghost** [comment]
Yes, I understand that you were trying to help us but reporting the issue. We are really thankful for that. But I was try to help you resolve your issue. Anyway, I checked on my system and it's working correctly. Thank you for raising it. In case if you come across any other issue, please feel free to contact us by visiting this URL: [http://www.packtpub.com/submit-errata](http://www.packtpub.com/submit-errata).
